[package]
name = "pkgdu"
version = "0.7.0"

authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]

description = "A tool to display packages disk usage size"
documentation = "https://github.com/bpetlert/pkgdu"
homepage = "https://github.com/bpetlert/pkgdu"
license = "GPL-3.0-or-later"
readme = "README.adoc"
repository = "https://github.com/bpetlert/pkgdu"

edition = "2021"
publish = false

[dependencies]
alpm = "2.2.2"
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
globset = "0.4.13"
humansize = "2.1.3"
once_cell = "1.18.0"
pacmanconf = "2.0.0"
regex = "1.9.6"
tabled = "0.14.0"
tracing = { version = "0.1.37", features = [
    "max_level_debug",
    "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
    "ansi",
    "env-filter",
    "fmt",
] }

[dev-dependencies]
duct = "0.13.6"
pretty_assertions = "1.4.0"
