[package]
name = "pkgdu"
version = "0.1.0"

edition = "2021"
publish = false

[dependencies]
alpm = "2.2.1"
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
humansize = "2.1.2"
pacmanconf = "2.0.0"
tabled = "0.10.0"
tracing = { version = "0.1.37", features = [
    "max_level_debug",
    "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = [
    "ansi",
    "env-filter",
    "fmt",
] }
